name: 'Pull Request Events to Slack'
description: 'Notify Slack about Pull Request events'
inputs:
  repoAccessToken:
    description: 'A repository Personal Access Token (PAT)'
    required: true
  repo:
    description: 'The repo to listen to for pull request events. Format is <OWNER>/<REPOSITORY>'
    required: true
  pullNumber:
    description: 'The pull request number to reference'
    required: true
  triggeringActor:
    description: 'The user/account that triggered the pull request event. I.e. Left a comment, change request, approved or merged a PR'
    required: true
outputs:
  slackMessage:
    description: 'Slack message body'
runs:
  using: "node16"
  main: "main.js"
