name: 'Pull Request Events to Slack'
description: 'Notifies Slack about Pull Request events'
inputs:
  repoAccessToken:
    description: 'repoAccessToken'
    required: true
  repo:
    description: 'repo name with owner in the front'
    required: true
  # owner:
  #   description: 'owner of repo'
  #   required: true
  pullNumber:
    description: 'pullNumber'
    required: false
    default: '1'
outputs:
  slackMessage:
    description: 'Slack message body'
runs:
  using: "node16"
  pre: "pre.js"
  pre-if: runner.os == 'linux'
  main: "main.js"
